---
micronaut:
  application:
    name: micronaut-neo4j-heroku

---
neo4j:
  encryption: true
  uri: ${GRAPHENEDB_BOLT_URL:`bolt://localhost`}
  username: ${GRAPHENEDB_BOLT_USER:`neo4j`}
  password: ${GRAPHENEDB_BOLT_PASSWORD:`neo4j`}
